// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChiTieu.Models;

#nullable disable

namespace QuanLyChiTieu.Migrations
{
    [DbContext(typeof(QuanLyChiTieuContext))]
    [Migration("20260404083648_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChiTieu.Models.Budget", b =>
                {
                    b.Property<string>("BudgetId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("budgetId");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoryId");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("limitAmount");

                    b.Property<string>("MonthYear")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("monthYear");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userId");

                    b.HasKey("BudgetId")
                        .HasName("PK__BUDGET__1E2B71364D1A2E66");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("BUDGET", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoryId");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("categoryName");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("type");

                    b.HasKey("CategoryId")
                        .HasName("PK__CATEGORY__23CAF1D853E3E3EC");

                    b.ToTable("CATEGORY", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("transactionId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoryId");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("transactionDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("walletId");

                    b.HasKey("TransactionId")
                        .HasName("PK__TRANSACT__9B57CF72CFF80705");

                    b.HasIndex("CategoryId");

                    b.HasIndex("WalletId");

                    b.ToTable("TRANSACTION", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.UserAccount", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__USER_ACC__CB9A1CFF29145B10");

                    b.ToTable("USER_ACCOUNT", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Wallet", b =>
                {
                    b.Property<string>("WalletId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("walletId");

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userId");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("walletName");

                    b.HasKey("WalletId")
                        .HasName("PK__WALLET__3785C8703C8EA1A6");

                    b.HasIndex("UserId");

                    b.ToTable("WALLET", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Budget", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__BUDGET__category__59063A47");

                    b.HasOne("QuanLyChiTieu.Models.UserAccount", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__BUDGET__userId__5812160E");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Transaction", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__TRANSACTI__categ__5535A963");

                    b.HasOne("QuanLyChiTieu.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("FK__TRANSACTI__walle__5441852A");

                    b.Navigation("Category");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Wallet", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.UserAccount", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__WALLET__userId__4D94879B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.UserAccount", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
